export {default as Categorias} from "./Categorias";
export {default as Footer} from "./Footer";
export {default as Header} from "./Header/Header";
export {default as ProfileDrop} from "./Header/ProfileDrop";
export {default as SortBar} from "./SortBar";
export {default as Sort} from "./Sort";
export {default as SliderBig} from "./Slider/SliderBig";
export {default as SliderMin} from "./Slider/SliderMin";
export {default as BookMark} from "./BookMark"
export {default as BookHome} from "./BookBlock/BookHome"
export {default as BookCatalog} from './BookBlock/BookCatalog'
export {default as BookMarkInPage} from './BookMarkInPage'