export {default as Home} from './Home'
export {default as Profile} from './Profile'
export {default as Catalog} from './Catalog'
export {default as Popular} from './Popular'
export {default as Subscription} from './Subscription'
export {default as BookPage} from './BookPage'